-- BD_TREE_MSGS — mensajes jerárquicos (app + contexto + índice por puntos)
CREATE SCHEMA IF NOT EXISTS "BD_TREE_MSGS";

CREATE TABLE IF NOT EXISTS "BD_TREE_MSGS"."MESSAGE" (
  "APP_ID" VARCHAR(64) NOT NULL,
  "CONTEXT_KEY" VARCHAR(256) NOT NULL,
  "TREE_PATH" VARCHAR(512) NOT NULL,
  "BODY" TEXT NOT NULL DEFAULT '',
  "JLOG" JSONB NOT NULL DEFAULT '{}'::jsonb,
  "ACTIVE" BOOLEAN NOT NULL DEFAULT TRUE,
  "ARCHIVED" BOOLEAN NOT NULL DEFAULT FALSE,
  "CREATED_AT" TIMESTAMPTZ NOT NULL DEFAULT now(),
  "UPDATED_AT" TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY ("APP_ID", "CONTEXT_KEY", "TREE_PATH")
);

CREATE INDEX IF NOT EXISTS "IX_MESSAGE_CTX_ACTIVE"
  ON "BD_TREE_MSGS"."MESSAGE" ("APP_ID", "CONTEXT_KEY", "ACTIVE", "UPDATED_AT" DESC);

CREATE INDEX IF NOT EXISTS "IX_MESSAGE_CTX_PATH"
  ON "BD_TREE_MSGS"."MESSAGE" ("APP_ID", "CONTEXT_KEY", "TREE_PATH");
